package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"zedgen/internal/parser"

	"github.com/ettle/strcase"
)

const (
	generatedFilePath          = "zschema"
	generatedFilenameExtension = ".zed.go"
)

type generatedFile struct {
	// File is the generated file.
	File *os.File
}

func (gf *generatedFile) P(args ...any) {
	// Write to the file
	for _, arg := range args {
		fmt.Fprint(gf.File, arg)
	}
	// Add a new line
	fmt.Fprintln(gf.File)
}

func generateFile(in *GenerateInput, schema []parser.Definition) error {
	fileName := "schema" + generatedFilenameExtension
	filePath := filepath.Join(in.OutputDir, generatedFilePath)
	if err := os.MkdirAll(filePath, 0755); err != nil {
		fmt.Printf("error creating directory %s: %v\n", filePath, err)
		return err
	}
	file, err := os.OpenFile(filepath.Join(filePath, fileName), os.O_CREATE|os.O_WRONLY, 0600)
	if err != nil {
		return err
	}
	defer file.Close()

	out := &generatedFile{File: file}

	generateHeader(out)
	out.P()
	out.P("package zschema")
	out.P()

	out.P("import (")
	out.P("	v1 \"github.com/authzed/authzed-go/proto/authzed/api/v1\"")
	out.P(")")
	generateBuilder(out)
	generateBaseInterfaces(out)
	generateBaseObjects(out, schema)

	return nil

}

func generateHeader(out *generatedFile) {

	out.P("// Code generated by zed-gen. DO NOT EDIT.")

}

func generateBuilder(out *generatedFile) {
	out.P("// Builder for writing, touching, or deleting relationships.")
	out.P("type RelBuilder struct {")
	out.P("	rels   []*v1.RelationshipUpdate")
	out.P("	action v1.RelationshipUpdate_Operation")
	out.P("}")
	out.P()
	out.P("// NewRelBuilder creates a new RelBuilder.")
	out.P("func NewRelBuilder() *RelBuilder {")
	out.P("	return &RelBuilder{}")
	out.P("}")
	out.P()
	out.P("// Sets the operation to RelationshipUpdate_OPERATION_CREATE")
	out.P("func (r *RelBuilder) Create() *RelBuilder {")
	out.P("	r.action = v1.RelationshipUpdate_OPERATION_CREATE")
	out.P("	return r")
	out.P("}")
	out.P()
	out.P("// Sets the operation to RelationshipUpdate_OPERATION_DELETE")
	out.P("func (r *RelBuilder) Delete() *RelBuilder {")
	out.P("	r.action = v1.RelationshipUpdate_OPERATION_DELETE")
	out.P("	return r")
	out.P("	}")
	out.P()
	out.P("// Sets the operation to RelationshipUpdate_OPERATION_TOUCH")
	out.P("func (r *RelBuilder) Update() *RelBuilder {")
	out.P("	r.action = v1.RelationshipUpdate_OPERATION_TOUCH")
	out.P("	return r")
	out.P("}")
	out.P()
	out.P("func (r *RelBuilder) perm(resource Objecter, rel Relationer, subject Objecter) *RelBuilder {")
	out.P("	up := &v1.RelationshipUpdate{")
	out.P("		Operation: r.action,")
	out.P("		Relationship: &v1.Relationship{")
	out.P("			Resource: &v1.ObjectReference{")
	out.P("				ObjectType: resource.Object(),")
	out.P("				ObjectId:   resource.Id(),")
	out.P("			},")
	out.P("			Relation: rel.String(),")
	out.P("			Subject: &v1.SubjectReference{")
	out.P("				Object: &v1.ObjectReference{")
	out.P("					ObjectType: subject.Object(),")
	out.P("					ObjectId:   subject.Id(),")
	out.P("				},")
	out.P("			},")
	out.P("		},")
	out.P("	}")
	out.P()
	out.P()
	out.P("	r.rels = append(r.rels, up)")
	out.P("	return r")
	out.P("}")
	out.P()
	out.P("// Build returns the list of relationships to be created, touched, or deleted.")
	out.P("func (r *RelBuilder) Build() []*v1.RelationshipUpdate {")
	out.P("	return r.rels")
	out.P("}")
	out.P()
}

func generateBaseInterfaces(out *generatedFile) {
	out.P("// Objecter is the interface for all objects.")
	out.P("type Objecter interface {")
	out.P("	Object() string")
	out.P("	String() string")
	out.P("	Relation() Relationer")
	out.P("	Id() string")
	out.P("}")
	out.P()
	out.P("// Deleter is the interface for all objects that can be deleted.")
	out.P("type Deleter interface {")
	out.P("	Object() string")
	out.P("	Id() string")
	out.P("	Relation() Relationer")
	out.P("}")
	out.P()
	out.P("type Relationer interface {")
	out.P("	String() string")
	out.P("}")
	out.P()
}

func generateBaseObjects(out *generatedFile, schema []parser.Definition) {
	for _, def := range schema {
		pascalName := strcase.ToGoPascal(def.Name)
		out.P("// ", pascalName, " is the object representing the ", def.Name, " resource.")
		out.P("type ", pascalName, " struct {")
		out.P("	id       string")
		out.P("	obj      string")
		out.P("	relation ", pascalName, "RelType")
		out.P("}")
		out.P()
		out.P("// ", pascalName, "RelType represents the valid relations for the ", def.Name, " resource.")
		out.P("type ", pascalName, "RelType string")
		out.P()
		out.P("func (s ", pascalName, "RelType) String() string {")
		out.P("	return string(s)")
		out.P("}")
		out.P()
		out.P("const (")
		for _, rel := range def.Relations {
			out.P("	// \"", rel.Name, "\" relation")
			out.P("	", pascalName, "RelType", strcase.ToGoPascal(rel.Name), " ", pascalName, "RelType = \"", rel.Name, "\"")
		}
		out.P(")")
		out.P()
		out.P("type ", pascalName, "PermissionType string")
		out.P()
		out.P("const (")
		for _, perm := range def.Permissions {
			out.P("	// \"", perm.Name, "\" permission")
			out.P("	", pascalName, "PermissionType", strcase.ToGoPascal(perm.Name), " ", pascalName, "PermissionType = \"", perm.Name, "\"")
		}
		out.P(")")
		out.P()
		out.P("func ", pascalName, "Obj(id string) *", pascalName, " {")
		out.P("	return &", pascalName, "{id: id, obj: \"", def.Name, "\"}")
		out.P("}")
		out.P()
		out.P("func (s ", pascalName, ") Object() string {")
		out.P("	return s.obj")
		out.P("}")
		out.P()
		out.P("func (s ", pascalName, ") Id() string {")
		out.P("	return s.id")
		out.P("}")
		out.P()
		out.P("func (s ", pascalName, ") Relation() Relationer {")
		out.P("	return s.relation")
		out.P("}")
		out.P()
		out.P("func (s ", pascalName, ") String() string {")
		out.P("	return \"", def.Name, ":\" + string(s.id)")
		out.P("}")
		out.P()
		out.P("// ", pascalName, "Relationship builds a ", def.Name, " relationship to be created, touched, or deleted.")
		out.P("func (r *RelBuilder) ", pascalName, "Relationship(", def.Name, " *", pascalName, ", rel ", pascalName, "RelType, subject Objecter) *RelBuilder {")
		out.P("	return r.perm(", def.Name, ", rel, subject)")
		out.P("}")
		out.P()
	}
}
